# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: YeongSik Ham
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "/" # the subpath of the site
url: "https://youngsikkk.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile_youngsikkk.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: hys7309.dev@gmail.com
    # - type: wechat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    # - type: twitter
    #   name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - type: facebook
    #   name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    # - type: linkedin
    #   name: LinkedIn
    #   link: http://linkedin.com/in/YourLinkedInUsername
    - type: github
      name: GitHub
      link: http://github.com/youngsikkk
    # - type: dribbble
    #   name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - type: rss
    #   name: RSS
    #   link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
